# Generator（生成器对象）

**生成器**对象是由一个 [generator function](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/function*) 返回的,并且它符合[可迭代协议](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#iterable)和[迭代器协议](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Iteration_protocols#iterator)。

# 语法

```javascript
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

let g = gen();
// "Generator { }"
```

# 方法

## `Generator.prototype.next()`

`next()` 方法返回一个包含属性 `done` 和 `value` 的对象。该方法也可以通过接受一个参数用以向生成器传值。

### 语法

```javascript
gen.next(value)
```

#### 参数

- `vlaue` 

  向生成器传递的值

#### 返回值

返回的`对象`包含两个属性：

- `done`（布尔类型）

  - 如果迭代器超过迭代序列的末尾，则值为 `true`。 在这种情况下，`value`可选地指定迭代器的返回值。
  - 如果迭代器能够生成序列中的下一个值，则值为`false`。 这相当于没有完全指定`done`属性。

- value 

  迭代器返回的任意`javascript`值。当`done`的值为`true`时可以忽略该值。



### 示例

#### 使用 `next()方法`

下面的例子展示了一个简单的生成器, 以及调用 `next` 后方法的返回值:

```javascript
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

var g = gen(); // "Generator { }"
g.next();      // "Object { value: 1, done: false }"
g.next();      // "Object { value: 2, done: false }"
g.next();      // "Object { value: 3, done: false }"
g.next();      // "Object { value: undefined, done: true }"
```

#### 向生成器传值

在此示例中，使用值调用`next`。 请注意，第一次调用没有记录任何内容，因为生成器最初没有产生任何结果。

```JavaScript
function* gen() {
  while(true) {
    var value = yield null;
    console.log(value);
  }
}

var g = gen();
g.next(1);
// "{ value: null, done: false }"
g.next(2);
// 2
// "{ value: null, done: false }"
```



## `Generator.prototype.return()`

`return()`方法返回给定的值并结束生成器

### 语法

```javascript
gen.return()
```

#### 参数

- `value`

  需要返回的值

#### 返回值

返回该函数参数给定的值

### 示例

#### 使用 `return()`

以下例子展示了一个简单的生成器和 `return` 方法的使用

```javascript
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

var g = gen();

g.next();        // { value: 1, done: false }
g.return("foo"); // { value: "foo", done: true }
g.next();        // { value: undefined, done: true }
```

如果对已经处于“完成”状态的生成器调用`return(value)`，则生成器将保持在“完成”状态。如果没有提供参数，则返回对象的`value`属性与示例最后的`.next()`方法相同。如果提供了参数，则参数将被设置为返回对象的`value`属性的值。

```JavaScript
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

var g = gen();
g.next(); // { value: 1, done: false }
g.next(); // { value: 2, done: false }
g.next(); // { value: 3, done: false }
g.next(); // { value: undefined, done: true }
g.return(); // { value: undefined, done: true }
g.return(1); // { value: 1, done: true }
```



## `Generator.prototype.throw()`

`throw()`方法用来向生成器抛出异常，并恢复生成器的执行，返回带有`done`和`value`两个属性的对象

### 语法

```javascript
gen.throw(exception)
```

#### 参数

- `exception`

  用于抛出的异常。 使用 [`Error`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error) 的实例对调试非常有帮助

#### 返回值

带有两个属性的`对象`：

- `done` (boolean)
  - 如果迭代器已经返回了迭代序列的末尾，则值为 `true`。在这种情况下，`可以`指定迭代器 `value `的返回值。 
  - 如果迭代能够继续生产在序列中的下一个值，则值为 `false`。 这相当与不指定 done 属性的值。
- `value` - 迭代器返回的任何 JavaScript 值。当 done 是 true 的时候可以省略。



### 示例

#### 使用 `throw()`

下面的例子展示了一个简单的生成器并使用 throw方法向该生成器抛出一个异常，该异常通常可以通过 `try...catch` 块进行捕获.

```javascript
function* gen() {
  while(true) {
    try {
       yield 42;
    } catch(e) {
      console.log("Error caught!");
    }
  }
}

var g = gen();
g.next(); // { value: 42, done: false }
g.throw(new Error("Something went wrong")); // "Error caught!"
```





# 示例

## 一个无限迭代器

```JavaScript
function* idMaker(){
    let index = 0;
    while(true)
        yield index++;
}

let gen = idMaker(); // "Generator { }"

console.log(gen.next().value);
// 0
console.log(gen.next().value);
// 1
console.log(gen.next().value);
// 2
// ...
```